### ISSUE TITLE
Add x86-64 support

### ISSUE THREAD

**Issue by rossburton** [aehs29/baremetal-helloqemu#2]
It would be great to use this as part of oeqa to verify newlib but without x86-64 it can't run in oe-selftest currently.

**Comment by ahcbb6** [comment]
Closing since support for x86-64 was added in:
https://github.com/aehs29/baremetal-helloqemu/commit/f42c92f1a487b75765f33376b9789a889fe13fd6

and oe-selftest support got merged into oe-core here:
https://git.yoctoproject.org/poky/commit/?id=293ae7b98ba957072af3271fe60be1c78d42478a
